version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_curso
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
      - 63306:3306